name: portfolio

services:
  server:
    image: hugomods/hugo:exts-non-root
    command: server -t terminal --navigateToChanged
    volumes:
      - ./:/src
      - ~/hugo_cache:/tmp/hugo_cache
    ports:
      - 1313:1313
