apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-raj
  labels:
    app: portfolio-raj
  namespace: rajsinghtech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-raj
  template:
    metadata:
      labels:
        app: portfolio-raj
    spec:
      volumes:
      - name: src-volume
        emptyDir: {}
      initContainers:
      - name: clone-repo
        image: alpine/git
        command:
        - sh
        - -c
        - |
          git clone --branch hugo https://github.com/rajsinghtech/portfolio.git /src
          chown -R 1000:1000 /src
        volumeMounts:
        - name: src-volume
          mountPath: /src
      containers:
      - name: server
        image: hugomods/hugo:exts-non-root
        command: ["server", "-t", "terminal"]
        ports:
        - containerPort: 1313
        volumeMounts:
        - name: src-volume
          mountPath: /src
        # - name: hugo-cache
        #   mountPath: /tmp/hugo_cache
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
